### ISSUE TITLE
Issue: Testing the trained model with random image

### ISSUE THREAD

**Issue by Addoxx** [adarshmalapaka/ground-plane-segmentation#2]
Hey guys! 

I have just installed the requirements and trying to test the model with a random image per usage.md

I get the following error:

Traceback (most recent call last):
  File "/ground-plane-segmentation/Codes/training/test.py", line 8, in <module>
    from model import PathModel
  File "/ground-plane-segmentation/Codes/training/model.py", line 2, in <module>
    import segmentation_models_pytorch as smp
  File "/ground-plane-segmentation/Codes/training/segmentation_models_pytorch/__init__.py", line 2, in <module>
    from . import encoders
  File "/ground-plane-segmentation/Codes/training/segmentation_models_pytorch/encoders/__init__.py", line 15, in <module>
    from .timm_efficientnet import timm_efficientnet_encoders
  File "/ground-plane-segmentation/Codes/training/segmentation_models_pytorch/encoders/timm_efficientnet.py", line 8, in <module>
    from timm.models.layers.activations import Swish
ModuleNotFoundError: No module named 'timm.models.layers.activations'

Please help

**Comment by Yan-0-0-Ye** [comment]
I got the error too. Have you solved it? Help

**Comment by Addoxx** [comment]
No, I dropped this project and haven't worked on it since. But going by the error, I suggest it has to do something with the PyTorch version.

**Comment by Yan-0-0-Ye** [comment]
Thanks!
